### PR TITLE
Show progress in git clone & 2 others

### PR DESCRIPTION
**Pull request by detj**
Added `--progress` flag of `git clone` which writes the standard progress to STDOUT. The tee-ed log file also receives the same output as tty but once the cloning completes, the log file gets truncated. Making the log file less useful.

I'll create another issue for fixing the truncating log file issue.

@sudhanshuraheja Let me know if you want any changes to be made. Also, [my commits will have emojis](https://github.com/dannyfritz/commit-message-emoji)

### CODE REVIEW

**Comment by detj** [comment]
**Fixes**
1. Show git clone progress
2. Fix xcpretty install with master password read from config.ci
3. Add checks for `iPhone` & `iPhoneOS` variables Fixes #14

**Comment by sudhanshuraheja** [comment]
@detj I'm not sure about removing the -n option. It just removes the trailing new line. Are you sure doing echo -ne does not work on your machine by echo -e does?

**Comment by detj** [comment]
`echo -ne` was not working on my machine. Man page of sudo says this about the `-S` flag

```
-S          The -S (stdin) option causes sudo to read the password from the standard input instead of the terminal device.  The password must be followed by a newline character.
```

So, I tried with `-n` removed and xcpretty installed in the next run. So, it seemed to work.

I don't know what the `-e` flag does for `echo`. Didn't find anything in the man page. So, I left it untouched.

**Comment by sudhanshuraheja** [comment]
@detj confirmed that echo -e works and echo -ne doesn't work.

**Pull request merged**
